version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:15.4-bookworm
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    
  redis:
    image: redis:alpine3.18
    container_name: redis_app
    ports:
      - "6379:6379"
    
  app:
    build:
      context: .
    env_file:
      - .env.production
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
    env_file:
      - .env.production
    container_name: celety_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
  
  flower:
    build:
      context: .
    env_file:
      - .env.production
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env.production
    ports:
      - "5050:80"
