"""Added stats to Post and Commet tables

Revision ID: aaaf7455c6d0
Revises: 20568dcaa854
Create Date: 2023-08-22 11:55:24.991747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaf7455c6d0'
down_revision: Union[str, None] = '20568dcaa854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_comments_id'), 'posts_comments', ['id'], unique=False)
    op.add_column('posts_posts', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('posts_posts', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_posts', 'likes')
    op.drop_column('posts_posts', 'views')
    op.drop_index(op.f('ix_posts_comments_id'), table_name='posts_comments')
    op.drop_table('posts_comments')
    # ### end Alembic commands ###
