"""posts table

Revision ID: 20568dcaa854
Revises: d93e7236b807
Create Date: 2023-08-21 20:13:54.409146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20568dcaa854'
down_revision: Union[str, None] = 'd93e7236b807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_posts_id'), 'posts_posts', ['id'], unique=False)
    op.create_index(op.f('ix_auth_roles_id'), 'auth_roles', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.drop_constraint('auth_users_role_id_fkey', 'auth_users', type_='foreignkey')
    op.create_foreign_key(None, 'auth_users', 'auth_roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_menu_header_menu_id'), 'menu_header_menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_header_menu_id'), table_name='menu_header_menu')
    op.drop_constraint(None, 'auth_users', type_='foreignkey')
    op.create_foreign_key('auth_users_role_id_fkey', 'auth_users', 'auth_roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_roles_id'), table_name='auth_roles')
    op.drop_index(op.f('ix_posts_posts_id'), table_name='posts_posts')
    op.drop_table('posts_posts')
    # ### end Alembic commands ###
